### ISSUE TITLE
Return Value

### ISSUE THREAD

**Issue by r3tex** [alandion/CUDAatomics.jl#2]
Hey, your source file is a bit dense and it wasn't obvious at a cursory glance how to add return types to the functions. It would be super useful if `atomicadd` returned the value after the add like the C version. Is this something you could add?

**Comment by alandion** [comment]
Good idea.  I'll add the return values for the next release, which will hopefully be very soon now that CUDAnative v2 is out

**Comment by alandion** [comment]
Actually, return values are already supported.  I forgot about that!.  I'm on latest CUDAnative, and master branch of CUDAatomics:

```
function kern_atomicadd( a, b, c )
    i = (blockIdx().x-1) * blockDim().x + threadIdx().x
    c[i] = b[i]
    k = atomicadd(a,b[i])
    c[i] += k
    return nothing
end

d_a = CuArray(zeros(Float32, 1))
d_b = CuArray(Float32.(collect(1:1024)))
d_c = CuArray(zeros(Float32, 1024))
@cuda threads=32 blocks=32 kern_atomicadd(d_a, d_b, d_c)

ascending_sums = sort(Array(d_c))
```
I can see `ascending_sums` has integer Float32 values with largest value equal to sum(d_b)

**Comment by alandion** [comment]
I should point out that, just like the C version, `atomicadd` returns the value *before* the add
